[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "nexa-api"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pandas",
    "requests"
]

[project.scripts]
main = "main:app"